### ISSUE TITLE
error when parsing file

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#131] opened 2017-03-02 22:00 UTC
```
*** Error: /media/psf/Home/Documents/Software/Annex60-git/Annex60/Resources/ReferenceResults/Dymola/Annex60_Fluid_HeatExchangers_Examples_AirHeater_T.txt could not be parsed.

Traceback (most recent call last):
  File "RunUnitTests.py", line 40, in <module>
    tester.run()
  File "/usr/local/lib/python2.7/dist-packages/buildingspy/development/regressiontest.py", line 2249, in run
    r = self._checkReferencePoints(ans)
  File "/usr/local/lib/python2.7/dist-packages/buildingspy/development/regressiontest.py", line 1600, in _checkReferencePoints
    data['ResultFile'], oldRefFulFilNam, y_sim, y_tra, refFilNam, ans)
  File "/usr/local/lib/python2.7/dist-packages/buildingspy/development/regressiontest.py", line 1243, in _compareResults
    old_results = self._readReferenceResults(oldRefFulFilNam)
  File "/usr/local/lib/python2.7/dist-packages/buildingspy/development/regressiontest.py", line 1148, in _readReferenceResults
    raise TypeError(detail)
TypeError: could not convert string to float: u289.149993896484375
```

I suppose this is the new buildingspy version? I tried to get it with pip but it tells me I'm already up to date. Is that possible?

**Comment by tsnouidui** [comment] 2017-03-02 22:24
@Mathadon The new hasn't been merged to the master yet. That must be something else.

**Comment by thorade** [comment] 2017-03-02 22:24
You should try a version newer than commit 3d7501d308cdd8d0607f1e693c2e24eafd246b06
Pip can install from GitHub directly like this:
pip install git+https://github.com

**Comment by thorade** [comment] 2017-03-02 22:25
There are a lot of new things on the master, but no new release on pypi

**Comment by mwetter** [comment] 2017-03-02 23:21
Try
```
pip install git+https://github.com/lbl-srg/BuildingsPy@master
```

**Comment by Mathadon** [comment] 2017-03-06 22:16
That does not seem to work. Also with the master version I get following error:
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 576: invalid start byte
```
Do you have an idea where this error may come from?

**Comment by mwetter** [comment] 2017-03-07 04:52
@Mathadon Do you use Python 2.7? There are some issues with encodings with BuildingsPy and Python 3.x.

**Comment by Mathadon** [comment] 2017-03-07 05:04
I use python 2.7.6

**Comment by thorade** [comment] 2017-03-07 08:32
I tried to port BuildingsPy to Python 3 (issue #94), because I am usually using Python 3, except for BuildingsPy. One of the improvements in Python 3 is that it is more clear/strict: bytes are bytes, strings are strings, all text is unicode, encoding is utf-8, conversions are usually explicit. 

Porting to Python 3 is easy, keeping it compatible with Python 2 is more difficult. The recommended approach is to use modern Python 3 code and then make it work on Python 2 by importing from future. One of these imports is a bit dangerous, it seems, the `from __future__ import unicode_literals` that was added in #121. What it does is basically prefix every string with `u` to tell Python2 that all strings are unicode as on Python 3. On Py3 it just does nothing, because strings are unicode anyway.

So, the first error that you reported was `TypeError: could not convert string to float: u289.149993896484375` (notice the u) but that was fixed by Michael in 3d7501d308cdd8d0607f1e693c2e24eafd246b06. It seems that after updating you now get a different error. Here are my ideas what you could try to fix that one: 
- Try if it works on Python 3. Now is a good time to switch.
- Send me the file that you are trying to open. Maybe it uses a wrong encoding? What does `file -i yourfile.mo` say? Does it contain anything that is not ascii? Try opening it in text mode explicitly, and possibly specify the encoding like `with open(copFilPat, mode="wt", encoding="utf-8") as fp:` I'll also try to reproduce the error by running IDEAS unit test on my computer.
- Comment the line `from __future__ import unicode_literals`. If that works, one could discuss to remove it.

**Comment by thorade** [comment] 2017-03-07 12:00
Turns out IDEAS had some non-ASCII characters in files that wer ASCII encoded.
Solved by https://github.com/open-ideas/IDEAS/pull/682

**Comment by Mathadon** [comment] 2017-03-07 22:44
@thorade thanks for fixing the characters!  let's hope they don't reappear.. 

Unfortunately I'm not familiar enough with python to do the upgrade right now. If I break stuff I'll notice it in a few weeks probably and I'll have no idea how to fix it :p I'll keep it in mind for next time.

**Comment by thorade** [comment] 2017-03-08 08:31
I didn't really expect that to happen. Allthough it is quite easy to use python2 and python3 side by side, especially on Ubuntu.

**Comment by thorade** [comment] 2017-04-05 18:17
@Mathadon I think this issue can be closed, there were some problems in IDEAS, and BuildingsPy does now always use utf-8 when opening files (utf-8-sig for reading and utf-8 for writing).

**Closed** 2017-04-18 18:19 UTC
