### ISSUE TITLE
inconsistent results due to dymola.mos

### ISSUE THREAD

**Issue by Mathadon** [lbl-srg/BuildingsPy#201] opened 2018-05-15 14:41 UTC
@mwetter Since a long time I’ve had different results than you when pulling IBPSA and I never really could figure out why. I attributed it to differences in the unit test setup on travis, but now that I have control over that setup too, I figured out that’s not the case. It now seems that the ~/dymola.mos script gets loaded when running unit tests, which I did not know. And I have following settings there that affect results:

```
Evaluate=true
Advanced.CompileWith64=2
Advanced.EfficientMinorEvents=true
```

It may be a good idea to somehow avoid this by including default settings in the unit test scripts, similar to the pedantic check?

**Comment by Mathadon** [comment] 2018-05-16 07:54
Actually, there still are some inconsistencies:

```
*** Warning: HeaterCooler_u.mat: con1.u_s has absolute and relative error = 1.000e+01, 3.299e-02.
             Maximum error is at t = 120.0
*** Warning: HeaterCooler_u.mat: con2.y has absolute and relative error = 1.000e+00, 1.000e+00.
             Maximum error is at t = 120.0
*** Warning: HeaterCooler_u.mat: con1.y has absolute and relative error = 1.000e+00, 1.000e+00.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: heaHigPow.TSet has absolute and relative error = 4.000e+01, 1.201e-01.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: cooLimPow.TSet has absolute and relative error = 5.000e+00, 1.735e-02.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: heaCooUnl.TSet has absolute and relative error = 5.000e+00, 1.735e-02.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: cooLimPow.Q_flow has absolute and relative error = 1.000e+03, 1.000e+00.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: heaHigPow.Q_flow has absolute and relative error = 1.000e+04, 1.000e+00.
             Maximum error is at t = 120.0
*** Warning: Validation_PrescribedOutlet.mat: heaCooUnl.Q_flow has absolute and relative error = 2.092e+03, 1.000e+00.
             Maximum error is at t = 120.0
*** Warning: StaticTwoPortConservationEquation.mat: modWatNoRev.conEqn.sta_b.T has absolute and relative error = 2.390e+00, 8.220e-03.
             Maximum error is at t = 900.0
*** Warning: StaticTwoPortConservationEquation.mat: modAirNoRev.conEqn.sta_b.T has absolute and relative error = 9.857e+00, 3.479e-02.
             Maximum error is at t = 900.0
*** Warning: StaticTwoPortConservationEquation.mat: modWatRev.conEqn.sta_b.T has absolute and relative error = 2.390e+00, 8.220e-03.
             Maximum error is at t = 900.0
*** Warning: StaticTwoPortConservationEquation.mat: modAirRev.conEqn.sta_b.T has absolute and relative error = 9.857e+00, 3.479e-02.
             Maximum error is at t = 900.0
*** Warning: StaticTwoPortConservationEquation.mat: QSen_flow.y has absolute and relative error = 1.000e+02, 1.000e+00.
             Maximum error is at t = 900.0
*** Warning: ConservationEquation.mat: dyn.Q_flow has absolute and relative error = 1.000e+02, 1.000e+00.
             Maximum error is at t = 900.0
*** Warning: ConservationEquation.mat: ste.sta_b.T has absolute and relative error = 4.780e+00, 1.658e-02.
             Maximum error is at t = 900.0
*** Warning: ControlledFlowMachine.mat: fan4.dp has absolute and relative error = 2.739e+04, 1.000e+00.
             Maximum error is at t = 60.0
*** Warning: ClosedLoop_y.mat: conPID.y has absolute and relative error = 2.500e-01, 9.930e-01.
             Maximum error is at t = 1800.0
*** Warning: ClosedLoop_y.mat: conPID.u_s has absolute and relative error = 5.000e-01, 2.000e+00.
             Maximum error is at t = 1800.0
*** Warning: MoverStages.mat: pump_y.m_flow has absolute and relative error = 8.006e-01, 1.000e+00.
             Maximum error is at t = 0.6
*** Warning: MoverStages.mat: pump_Nrpm.m_flow has absolute and relative error = 8.895e-01, 1.000e+00.
             Maximum error is at t = 0.6
*** Warning: MoverStages.mat: pump_dp.m_flow has absolute and relative error = 1.414e+00, 4.142e-01.
             Maximum error is at t = 0.3
*** Warning: MoverStages.mat: pump_m_flow.m_flow has absolute and relative error = 1.000e+00, 1.000e+00.
             Maximum error is at t = 0.6
*** Warning: TemperatureDryBulb.mat: temSteSta.T has absolute and relative error = 1.000e+01, 3.299e-02.
             Maximum error is at t = 15.0
*** Warning: TemperatureDryBulb.mat: masFloRat.ports[1].m_flow has absolute and relative error = 1.000e+00, 0.000e+00.
             Maximum error is at t = 15.0
```

these differences always occur at a time event, which is generated by a `Table` or a `Step` block. So it is somehow related to whether the result from before or after the event is saved. Have you had similar problems before?

**Comment by thorade** [comment] 2018-05-16 08:00
To my understanding, this issue and also #49 could be resolved by using the tube/tunnel comparison approach as used in csv-compare. Probably there is still some tiny difference in the setup!?

**Comment by Mathadon** [comment] 2018-05-16 08:26
I just did a test where I ran the same unit test using 'Store variables at events' enabled and disabled. This produces different results for the equidistant sample points at the event.

E.g. running `Resources/Scripts/Dymola/Fluid/HeatExchangers/Validation/HeaterCooler_u.mos` with both options and 

```
from buildingspy.io.outputfile import Reader
resultFile="HeaterCooler_u.mat"
r=Reader(resultFile, "dymola")
r.values('con1.u_s')[0][50]
```
produces
```
>>> 303.14999
>>> 293.14999 
``` 
depending on 'Store variables at events'. Also, when storing at events, two result points are saved. Dymola apparently now has an option for this ('Number of results to keep').

When not storing variables at events, the variable value of after the event is stored. However, Buildingspy by default returns the first point in the interpolate function of `Plotter`:

```
        for i in range(1, iMax):
            if t[i] > t[i - 1] + tTol:
                tNew.append(t[i])
                yNew.append(y[i])
            else:
                if t[i] != t[i - 1] and t[i - 1] + tInc < maxT:
                    if t[i - 1] + tInc < t[i + 1]:
                        tNew.append(t[i - 1] + tInc)
                        yNew.append(y[i])
``` 
in https://github.com/lbl-srg/BuildingsPy/blob/master/buildingspy/io/postprocess.py

one solution could thus be to change this default behavior by modifying this snippet into:

```
        for i in range(1, iMax):
            if t[i] > t[i - 1] + tTol:
                tNew.append(t[i])
                yNew.append(y[i])
            else:
                if t[i] == t[i - 1]:
                    yNew[-1]=y[i] // did not verify syntax
                elif t[i - 1] + tInc < maxT:
                    if t[i - 1] + tInc < t[i + 1]:
                        tNew.append(t[i - 1] + tInc)
                        yNew.append(y[i])
``` 
?

Another option could be to force the unit tests to set a variable for `__Dymola_experimentSetupOutput(events=false)` but this is more work for the developers.

**Comment by Mathadon** [comment] 2018-05-16 08:41
@thorade I don't think the tube would help here, since there are temperature differences of 10 K at that point in time?

**Comment by thorade** [comment] 2018-05-16 08:44
The tube also compares the value in the time direction (or, in all directions, like a circle around the point), exactly to avoid error messages due to events. At least that is how I understood that.

If there are two equal results, but one has an event a millisecond earlier, then BuildingsPy would report an error. But I am unsure whether it sure be considered an error.

**Comment by thorade** [comment] 2018-05-16 08:53
I tried to ask a related question on SO some time ago:
https://stackoverflow.com/questions/46316442/compare-two-time-series-simulation-results
In the diagram shown in that question, I would say that your example would have been accepted as equal result.

**Comment by thorade** [comment] 2018-05-16 09:05
In an ideal world, Modelica would have a free unit testing library, and a common format for storing reference results, and then multiple tools for executing the tests. The common format should probably store two values at events, and it should be some standard (csv, json, hdf5, whatever), and it should be text-based so that it works well with git.
https://stackoverflow.com/questions/36157220/unit-testing-modelica-component-library

**Comment by Mathadon** [comment] 2018-05-16 09:11
Let's start lobbying ;)

**Comment by thorade** [comment] 2018-05-16 09:15
I already did, in Prague, see presentation 10 (and also 1) here:
https://modelica.org/events/modelica2017/partners/vendor-sessions-and-tutorials

**Comment by Mathadon** [comment] 2018-05-16 10:26
It just got even more fun.. 
I reran unit tests on my PC and on travis using the proposed solution, as implemented in https://github.com/Mathadon/BuildingsPy/tree/issue201_interpolate . This creates more problems. E.g. for `IBPSA.Controls.Continuous.Examples.LimPID` not one but _three_ results are saved (E.g. at `t=0.25`) when using 'Output at events'. The first two results are the same (0) while the third is different (1). When not using 'Output at events'. only one result is generated 0. I.e. it looks like the second result is returned.. The proposed fix therefore does not work, since it uses the last result. 

I could try to fix it by using the second result instead of the last, but that hardly looks like a robust solution. Instead, it would make sense to use `__Dymola_experimentSetupOutput(events=false/true)` such that the same number of results is generated, regardless of what machine is used. Is this something that we can include in the unit test script?

**Comment by Mathadon** [comment] 2018-05-16 12:04
I added `__Dymola_experimentSetupOutput(events=true)` to the 8 failing tests. I reran the unit tests locally, which produced new results for 2 of the 8 tests. However, all tests then produced consistent results when cross-checking on Travis. This seems to suggest that both the local machine and travis choose different default values for different tests.. 

This solved my problem for now, but the issue will re-appear when merging IBPSA into IDEAS so it would be good to have a more robust solution to this problem. Any suggestions that do not involve adding `__Dymola_experimentSetupOutput(events=true)` to each unit test?

**Comment by thorade** [comment] 2018-05-16 12:14
The other workaround could be to always use the identical docker image locally and on Travis to generate reference results and to run the regression tests.
What is your local machine now? VirtualBox with Ubuntu 16.04 on MacOS?

**Comment by Mathadon** [comment] 2018-05-16 12:16
Running parallels - Ubuntu 14.04 on osx
Using docker is indeed a solution.. Although that complicates the development and debugging of the unit test scripts :)

**Comment by thorade** [comment] 2018-05-16 12:27
The docker image uses Ubuntu 16.04, could be the reason for the differences!?

**Comment by Mathadon** [comment] 2018-05-16 12:51
Running gcc 4.8.5. 

Sounds too complex for me :) I rather fix the actual problem than trying to work around it like this!

**Comment by Mathadon** [comment] 2018-05-19 22:09
@mwetter, I will look into this!

**Comment by mwetter** [comment] 2018-05-21 20:39
@Mathadon Thanks, these are good suggestions.

**Comment by mwetter** [comment] 2018-05-23 15:58
Closed as it has been merged to the master.

**Closed by mwetter** 2018-05-23 15:58 UTC
