### ISSUE TITLE
Err when running Example of Simulating a model with two different parameter values

### ISSUE THREAD

**Issue by jli113** [lbl-srg/BuildingsPy#179] opened 2017-11-21 02:17 UTC
I'm using Python 3.6 running this Simulating a model with two different parameter values. The err of AttributeError: 'NoneType' object has no attribute 'write' occurred using Pool.
When running 'Simulating a model with two different parameter values but without recompilation' and 'Plotting of Time Series', it returned the error of NameError: name 'exit' is not defined.

**Comment by thorade** [comment] 2017-11-21 11:54
Python 3 support was added in #94. Since then, no new release to PyPI has been made:
https://pypi.python.org/pypi/buildingspy
So maybe your uissue can be fixed by just installing the latest master by running
```
python -m pip install --upgrade https://github.com/lbl-srg/BuildingsPy/archive/master.zip
```
If it still fails then, we would have to test whether it is a Py2/Py3 issue or something else, and for that we would need a script that triggers your error or at least instructions how to reproduce it.

**Comment by jli113** [comment] 2017-11-27 15:47
Thanks, sorry for my delay.  I reinstalled the latest version yet the failure remained. I'm using Anaconda. Should this be the cause?

runfile('C:/Users/J.LI/Desktop/temp.py', wdir='C:/Users/J.LI/Desktop')
Traceback (most recent call last):

  File "<ipython-input-2-5c81fd0cc9f3>", line 1, in <module>
    runfile('C:/Users/J.LI/Desktop/temp.py', wdir='C:/Users/J.LI/Desktop')

  File "C:\Users\J.LI\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\J.LI\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/J.LI/Desktop/temp.py", line 54, in <module>
    main()

  File "C:/Users/J.LI/Desktop/temp.py", line 46, in main
    po.map(simulateCase, li)

  File "C:\Users\J.LI\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "C:\Users\J.LI\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

AttributeError: 'NoneType' object has no attribute 'write'

**Comment by thorade** [comment] 2017-11-27 16:32
I am also using Anaconda3 and Python 3.6 on Windows 10, so this should not be causing a problem.
Could you post a small example script that will reproduce the error you are getting, maybe the content of that temp.py file?
Did you run the script from spyder or did you also try running it from the console directly?

**Comment by jli113** [comment] 2017-11-28 12:59
Yes, I ran it with Spyder. The codes are copied directly from the tutorial.

**Comment by thorade** [comment] 2017-11-28 13:35
OK, so that is the first example from
http://simulationresearch.lbl.gov/modelica/buildingspy/examples.html

On Linux, I can run the example with Python2 as well as with Python 3.5,
but on my Windows box I am also getting some errors.

**Comment by thorade** [comment] 2017-11-28 13:50
This seems to be due to running it from Spyder through IPython on Windows:
https://stackoverflow.com/questions/32489352/multiprocessing-program-has-attributeerror-in-anaconda-notebook
I ran it from an IPython Notebook, on Windows and on Linux, and on Linux it worked, but on Windows it failed. Running it from a normal terminal worked, also on Windows.

But on Windows, it was also very slow, because the Windows Antimalware Service Executable was consumig all CPU resources!?

**Comment by jli113** [comment] 2017-11-29 05:01
So basically, it was because I ran it on Windows...
Thanks a lot.

**Closed** 2017-11-29 05:01 UTC

**Comment by Magdaanne** [comment] 2018-02-03 08:57
Did you find a solution for running it on Windows? When I start the example, (from normal terminal) it seems like the simulation starts, but "never" ends. I quitted it after 20 minutes ..

**Comment by thorade** [comment] 2018-02-03 19:03
One solution would be to remove the multiprocessing and run it in a single thread. Other solutions are discussed elsewhere, this is really a general "python multiprocessing on Windows" issue rather than a BuildingsPy issue. Still, it would be good to change the example such that it can be run without errors, but I  currently do not know how (maybe someone else knows it?).
